# Generated by Django 3.2 on 2021-06-12 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=30, verbose_name='Municipio')),
                ('colonia', models.CharField(max_length=30, verbose_name='Colonia')),
                ('calle', models.CharField(max_length=50, verbose_name='Calle')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Almacen',
                'verbose_name_plural': 'Almacenes',
                'db_table': 'almacenes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('sku', models.BigIntegerField(unique='True', verbose_name='Sku')),
                ('nombre_prod', models.CharField(max_length=25, verbose_name='Producto')),
                ('categoria', models.CharField(max_length=25, verbose_name='Categoria')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('cotizacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cotización')),
                ('precio_de_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de venta')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo unitario')),
                ('costo_paquete', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo por paquete')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id_sucursal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.almacenes', verbose_name='Sucursal')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono fijo')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursales',
                'ordering': ['id_sucursal'],
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=30, verbose_name='Municipio')),
                ('colonia', models.CharField(max_length=30, verbose_name='Colonia')),
                ('calle', models.CharField(max_length=50, verbose_name='Calle')),
                ('fecha_de_venta', models.DateTimeField(auto_now=True, verbose_name='Fecha de venta')),
                ('estado_de_venta', models.CharField(choices=[('Vendido', 'Vendido'), ('Pendiente', 'Pendiente')], max_length=25, verbose_name='Estado de venta')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto total')),
                ('productos', models.ManyToManyField(to='main.Productos')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=30, verbose_name='Nombre comercial')),
                ('nombre_representante', models.CharField(max_length=30, verbose_name='Nombre del representante')),
                ('tel_movil', models.CharField(max_length=20, verbose_name='Telefono movil')),
                ('tel_fijo', models.CharField(max_length=20, verbose_name='Telefono fijo')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('municipio', models.CharField(max_length=30, verbose_name='Municipio')),
                ('colonia', models.CharField(max_length=30, verbose_name='Colonia')),
                ('calle', models.CharField(max_length=50, verbose_name='Calle')),
                ('pagina_web', models.CharField(max_length=200, verbose_name='Pagina web')),
                ('productos', models.ManyToManyField(to='main.Productos')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='almacenes',
            name='productos',
            field=models.ManyToManyField(to='main.Productos'),
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agua', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Agua')),
                ('renta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Renta')),
                ('luz', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Luz')),
                ('internet', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Internet')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sucursales')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'db_table': 'gastos',
                'ordering': ['id'],
            },
        ),
    ]
