# Generated by Django 3.2 on 2021-06-13 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gastos_fecha_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursales',
            options={'ordering': ['sucursal'], 'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.RenameField(
            model_name='sucursales',
            old_name='id_sucursal',
            new_name='sucursal',
        ),
    ]
