# Generated by Django 3.2 on 2021-06-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210613_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha_de_venta',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de venta'),
        ),
    ]
